const express=require("express"),cookieParser=require("cookie-parser"),jwt=require("jsonwebtoken"),fs=require("fs"),path=require("path");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"CHANGE_THIS_SECRET",ADMIN_USER=process.env.ADMIN_USER||"admin",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"ChangeMe123!";
const DB=path.join(__dirname,"data/db.json"); const load=()=>JSON.parse(fs.readFileSync(DB,"utf8")); const save=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2)); const nid=a=>a.length?Math.max(...a.map(x=>x.id))+1:1;
app.use(express.json({limit:"2mb"}));app.use(express.urlencoded({extended:true}));app.use(cookieParser());app.use(express.static(path.join(__dirname,"public")));
function auth(req,res,next){try{req.admin=jwt.verify(req.cookies.vh_admin,SECRET);next()}catch(e){res.status(401).json({error:"Unauthorized"})}}
app.get("/api/countries",(q,s)=>s.json(load().countries));
app.get("/api/countries/:slug",(q,s)=>{let d=load(),c=d.countries.find(x=>x.slug===q.params.slug);if(!c)return s.status(404).json({error:"Country not found"});s.json({...c,packages:d.packages.filter(p=>p.country===c.slug&&p.active)})});
app.post("/api/enquiries",(q,s)=>{let d=load(),x={id:nid(d.enquiries),createdAt:new Date().toISOString(),status:"new",...q.body};d.enquiries.push(x);save(d);s.json({ok:true,id:x.id})});
app.post("/api/bookings",(q,s)=>{let d=load(),x={id:nid(d.bookings),createdAt:new Date().toISOString(),status:"pending",...q.body};d.bookings.push(x);save(d);s.json({ok:true,bookingId:"VH"+String(x.id).padStart(5,"0")})});
app.post("/api/admin/login",(q,s)=>{if(q.body.username!==ADMIN_USER||q.body.password!==ADMIN_PASSWORD)return s.status(401).json({error:"Invalid login"});s.cookie("vh_admin",jwt.sign({username:ADMIN_USER,role:"admin"},SECRET,{expiresIn:"8h"}),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:28800000});s.json({ok:true})});
app.post("/api/admin/logout",(q,s)=>{s.clearCookie("vh_admin");s.json({ok:true})});app.get("/api/admin/me",auth,(q,s)=>s.json({ok:true,user:q.admin.username}));
app.get("/api/admin/dashboard",auth,(q,s)=>{let d=load();s.json({countries:d.countries.length,packages:d.packages.length,bookings:d.bookings.length,enquiries:d.enquiries.length})});
app.get("/api/admin/packages",auth,(q,s)=>s.json(load().packages));
app.post("/api/admin/packages",auth,(q,s)=>{let d=load(),x={id:nid(d.packages),active:true,featured:false,itinerary:[],inclusions:[],exclusions:[],...q.body,price:Number(q.body.price||0)};d.packages.push(x);save(d);s.json(x)});
app.put("/api/admin/packages/:id",auth,(q,s)=>{let d=load(),i=d.packages.findIndex(x=>x.id==q.params.id);if(i<0)return s.status(404).json({error:"Not found"});d.packages[i]={...d.packages[i],...q.body,id:d.packages[i].id,price:Number(q.body.price??d.packages[i].price)};save(d);s.json(d.packages[i])});
app.delete("/api/admin/packages/:id",auth,(q,s)=>{let d=load();d.packages=d.packages.filter(x=>x.id!=q.params.id);save(d);s.json({ok:true})});
app.get("/api/admin/countries",auth,(q,s)=>s.json(load().countries));
app.post("/api/admin/countries",auth,(q,s)=>{let d=load(),x={id:nid(d.countries),status:"active",...q.body};d.countries.push(x);save(d);s.json(x)});
app.put("/api/admin/countries/:id",auth,(q,s)=>{let d=load(),i=d.countries.findIndex(x=>x.id==q.params.id);if(i<0)return s.status(404).json({error:"Not found"});d.countries[i]={...d.countries[i],...q.body,id:d.countries[i].id};save(d);s.json(d.countries[i])});
app.get("/api/admin/bookings",auth,(q,s)=>s.json(load().bookings.reverse()));
app.put("/api/admin/bookings/:id",auth,(q,s)=>{let d=load(),i=d.bookings.findIndex(x=>x.id==q.params.id);if(i<0)return s.status(404).json({error:"Not found"});d.bookings[i]={...d.bookings[i],...q.body};save(d);s.json(d.bookings[i])});
app.get("/api/admin/enquiries",auth,(q,s)=>s.json(load().enquiries.reverse()));
app.get("/admin",(q,s)=>s.sendFile(path.join(__dirname,"public/admin.html")));app.get("/country/:slug",(q,s)=>s.sendFile(path.join(__dirname,"public/country.html")));app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public/index.html")));
app.listen(PORT,()=>console.log("Ved Holidays running on "+PORT));